name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 3.0.0
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/chatview

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  any_link_preview: 3.0.3
  cached_network_image: 3.4.1
  chatview_utils: 3.0.0

  intl: 0.20.2
  url_launcher: 6.3.2

  scroll_to_index: ^3.0.1
dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
